# Generated by Django 4.2.4 on 2024-09-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0002_remove_book_available_copies_book_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowed_books',
            options={'verbose_name_plural': 'Borrowed Books'},
        ),
        migrations.AddField(
            model_name='borrowed_books',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
