# Generated by Django 4.2.4 on 2024-09-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0003_alter_borrowed_books_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='category',
        ),
    ]
