# Generated by Django 4.2.4 on 2024-09-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
